AllCops:
  TargetRubyVersion: 2.0

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 999

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Style/AccessorMethodName:
  Exclude:
    - 'lib/dogtrainer/api.rb'

Style/PreferredHashMethods:
  Exclude:
    - 'lib/dogtrainer/api.rb'

Metrics/BlockLength:
  Max: 3000

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'lib/dogtrainer/api.rb'

Performance/Caller:
  Exclude:
    - 'lib/dogtrainer/api.rb'

Performance/HashEachMethods:
  Exclude:
    - 'lib/dogtrainer/api.rb'
