#Lint/UselessAssignment:
#  Exclude:
#    - 'lib/dogtrainer/api.rb'
#    - 'spec/unit/api_spec.rb'

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 999

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 20

Style/AccessorMethodName:
  Exclude:
    - 'lib/dogtrainer/api.rb'

Style/PreferredHashMethods:
  Exclude:
    - 'lib/dogtrainer/api.rb'
